[package]
name = "cargo-patch"
version = "0.1.13"
authors = ["Marc Mettke <marc@itmettke.de>"]
edition = "2021"
description = "Cargo Subcommand for patching dependencies using patch files"
license-file = "LICENSE"
repository = "https://github.com/mettke/cargo-patch"
readme = "README.md"
keywords = ["cargo", "patch", "dependency", "dependencies", "patchfile"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
cargo = "0.62"
failure = "0.1"
fs_extra = "1.2"
patch = "0.6"
semver = "1.0"
toml_edit = "0.14"

[dev-dependencies]
cargo-test-macro = { git = "https://github.com/rust-lang/cargo.git", version = "0.1.0", tag = "0.61.0" }
cargo-test-support = { git = "https://github.com/rust-lang/cargo.git", version = "0.1.0", tag = "0.61.0" }
